### ISSUE TITLE
Support for non Rails applications?

### ISSUE THREAD

**Issue by yoshz** [sgruhier/capistrano-db-tasks#53]
I like the idea how this library works and would like to use it for my (php) applications.
However it seems primary focussed for Rail applications which I have no experience with. How could I make the sync tasks work for any other kind of application?

**Comment by dmitry** [comment]
@yoshz you need to add `/config/database.yml` file, with some contents like:

```
production:
  adapter: mysql
  encoding: utf8
  database: your_db
  username: root
  password: your_pass
  socket: /tmp/mysql.sock
  host: your_db_ip
  port: 3306           
```

In this case you will also need to set:

```
set :rails_env, "production"
```

In your capistrano file.
