### ISSUE TITLE
db:pull without providing ENV password and username?

### ISSUE THREAD

**Issue by karlingen** [sgruhier/capistrano-db-tasks#74]
In database.yml on my production server I define my database keys like this: 

```yaml
production:
  database: awesome_app_production
  pool: 25
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
```
And when pulling the database to my local environment I need to do this:
```
$ cap production db:pull DATABASE_USERNAME=my_username DATABASE_PASSWORD=my_password
```

Is there a way of letting `capistrano-db-tasks` to automatically pull the information from the `.rbenv-vars` located in the shared folder on the production folder? That is where I enter database credentials and environment variables since I'm using [rbenv-vars](https://github.com/sstephenson/rbenv-vars).

It would be nice to be able to only run `cap production db:pull`
